title: Sangria
description: "Sangria - Scala GraphQL Implementation"
baseurl: ""
url: "http://sangria-graphql.org"
theme: flatly
ga-code: UA-65759630-1
domain: scaldi.org

version:
  sangria: 0.1.0

groupId: com.github.olegilyenko

link:
  sangria-github: https://github.com/sangria-graphql
  sangria-maven: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.olegilyenko%22
  sangria-releases: https://github.com/OlegIlyenko/sangria/releases
  twitter: https://twitter.com/easyangel
  stack-overflow: http://stackoverflow.com/questions/tagged/sangria
  stack-overflow-ask: http://stackoverflow.com/questions/ask?tags=scala,graphql,sangria
  google-groups: https://groups.google.com/forum/#!forum/sangria-graphql
  sangria-changelog: https://github.com/OlegIlyenko/sangria/blob/master/CHANGELOG.md
  repo:
    sangria: https://github.com/OlegIlyenko/sangria
  maven:
    sangria: http://search.maven.org/#artifactdetails%7Ccom.github..olegilyenko%7Csangria_
  issues:
    sangria: https://github.com/OlegIlyenko/sangria/issues
  website: https://github.com/sangria-graphql/sangria-website
  jekyll: http://jekyllrb.com/
  ghpages: https://pages.github.com/

markdown: kramdown
permalink: pretty

gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
