title: Sangria
description: "Sangria - Scala GraphQL Implementation"
baseurl: ""
url: "http://sangria-graphql.org"
theme: flatly
ga-code: UA-65759630-1
domain: sangria-graphql.org

version:
  sangria: 0.2.1

groupId: org.sangria-graphql

link:
  sangria-github: https://github.com/sangria-graphql
  sangria-maven: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.sangria-graphql%22
  sangria-releases: https://github.com/sangria-graphql/sangria/releases
  twitter: https://twitter.com/easyangel
  stack-overflow: http://stackoverflow.com/questions/tagged/sangria
  stack-overflow-ask: http://stackoverflow.com/questions/ask?tags=scala,graphql,sangria
  google-groups: https://groups.google.com/forum/#!forum/sangria-graphql
  sangria-changelog: https://github.com/sangria-graphql/sangria/blob/master/CHANGELOG.md
  repo:
    sangria: https://github.com/sangria-graphql/sangria
  maven:
    sangria: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria_
  issues:
    sangria: https://github.com/sangria-graphql/sangria/issues
  website: https://github.com/sangria-graphql/sangria-website
  jekyll: http://jekyllrb.com/
  ghpages: https://pages.github.com/
  graphql: http://facebook.github.io/graphql/
  akka-http-example:
    github: https://github.com/sangria-graphql/sangria-akka-http-example
    activator: https://www.typesafe.com/activator/template/sangria-akka-http-example
  try: http://try.sangria-graphql.org

markdown: kramdown
permalink: pretty

gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
